version: "3"
services:
  googlephotobackup:
    build: .
    environment:
      - CRON=${CRON}
      - HEALTHCHECK_HOST=${HEALTHCHECK_HOST}
      - HEALTHCHECK_ID=${HEALTHCHECK_ID}
      - INITIAL_PHOTO_URL=${INITIAL_PHOTO_URL}
      - WRITE_SCRAPED_EXIF=${WRITE_SCRAPED_EXIF}
      - FLAT_DIRECTORY_STRUCTURE=${FLAT_DIRECTORY_STRUCTURE}

    volumes:
      - ./session:/session
      - ./library:/download
    restart: unless-stopped