version: "3"
services:
  googlephotobackup:
    image: prigal/google-photos-backup:latest
    environment:
      - CRON=${CRON}
      - HEALTHCHECK_HOST=${HEALTHCHECK_HOST}
      - HEALTHCHECK_ID=${HEALTHCHECK_ID}
      - INITIAL_PHOTO_URL=${INITIAL_PHOTO_URL}
      - WRITE_SCRAPED_EXIF=${WRITE_SCRAPED_EXIF}
      - FLAT_DIRECTORY_STRUCTURE=${FLAT_DIRECTORY_STRUCTURE}
      - BROWSER_LOCALE=${BROWSER_LOCALE}
      - BROWSER_TIMEZONE_ID=${BROWSER_TIMEZONE_ID}
    volumes:
      - ./session:/session
      - ./library:/download
    restart: unless-stopped